<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJidOzQD\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJidOzQD/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJidOzQD.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJidOzQD\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJidOzQD\appAppKernelProdContainer([
    'container.build_hash' => 'JidOzQD',
    'container.build_id' => 'a816edf3',
    'container.build_time' => 1736459299,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJidOzQD');
